"""Deterministic seed list of known AI startups for entity resolution.

The list contains 50 canonical startup names. It can be extended in the future
without affecting deterministic behaviour.
"""

SEED_STARTUPS = [
    "OpenAI",
    "Anthropic",
    "DeepMind",
    "Scale AI",
    "Cohere",
    "AI21 Labs",
    "Stability AI",
    "Hugging Face",
    "DataRobot",
    "SambaNova",
    "Pinecone",
    "Weaviate",
    "Snorkel AI",
    "Clarifai",
    "Cerebras",
    "LatticeFlow",
    "Runway AI",
    "MosaicML",
    "Adept AI",
    "Iterate.ai",
    "Primer",
    "Vicarious",
    "Kensho",
    "Vantage",
    "Element AI",
    "Graphcore",
    "Fiddler Labs",
    "OctoML",
    "Synthekine",
    "Peltarion",
    "Zetane",
    "Arize AI",
    "Mindstrong",
    "Neuralink",
    "Lumiata",
    "Kite",
    "Automation Anywhere",
    "C3.ai",
    "Dataiku",
    "H2O.ai",
    "Abacus.AI",
    "Syntasa",
    "Databricks",
    "Snowflake",
    "Google DeepMind",
    "Microsoft AI",
    "Amazon AI",
    "IBM Watson",
    "Baidu AI",
    "Tencent AI",
    "Alibaba DAMO",
    "OpenAI Labs",
]
